helper-status-checker:
  enabled: true
  approver: true
  checks:
    - operatorName: cluster-logging 
      subscriptionName: cluster-logging
      namespace:
        name: openshift-logging
      serviceAccount:
        name: "status-checker"


serviceAccount: logcollector

clustername: ""
csv: ""
roleArn: ""
region: ""
