apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aap-postgresql-secretstore
  namespace: aap
  annotations:
    ## Add this annotation to disable controller warning events for unmaintained stores
    external-secrets.io/disable-maintenance-checks: "true"
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  # You can specify retry settings for the http connection
  # these fields allow you to set a maxRetries before failure, and
  # an interval between the retries.
  # Current supported providers: AWS, Hashicorp Vault, IBM
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  # provider field contains the configuration to access the provider
  # which contains the secret exactly one provider must be configured.
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: aws-secret-manager
            namespace: aap