apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocds.argoproj.io/name: openshift-gitops
    argocds.argoproj.io/namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/name: openshift-gitops
    app.kubernetes.io/part-of: argocd
  name: cluster-gitops-argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-gitops-argocd-application-controller
subjects:
- kind: ServiceAccount
  name: cluster-gitops-argocd-application-controller
  namespace: openshift-gitops
