apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: custom-alerts
  namespace: {{ .Values.namespace }}
  name: imagestreams-rules
spec:
  groups:
  - name: imagestreams.rules
    rules:
    - expr: sum by (location, source) (image_registry_image_stream_tags_total)
      record: imageregistry:imagestreamtags_count:sum
