apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: custom-alerts
  namespace: {{ .Values.namespace }}
  name: machine-config-controller
spec:
  groups:
  - name: os-image-override.rules
    rules:
    - expr: sum(os_image_url_override)
      record: os_image_url_override:sum
  - name: mcc-drain-error
    rules:
    - alert: MCCDrainError
      annotations:
        description: 'Drain failed on {{ "{{" }} $labels.exported_node {{ "}}" }} , updates may be
          blocked. For more details check MachineConfigController pod logs: oc logs
          -f -n {{ "{{" }} $labels.namespace {{ "}}" }} machine-config-controller-xxxxx -c machine-config-controller'
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/machine-config-operator/MachineConfigControllerDrainError.md
        summary: Alerts the user to a failed node drain. Always triggers when the
          failure happens one or more times.
      expr: |
        mcc_drain_err > 0
      labels:
        #namespace: openshift-machine-config-operator
        severity: warning
        customer: "true"
        namespace: {{ .Values.namespace }}
  - name: mcc-pool-alert
    rules:
    - alert: MCCPoolAlert
      annotations:
        description: 'Node {{ "{{" }} $labels.exported_node {{ "}}" }} has triggered a pool alert
          due to a label change. For more details check MachineConfigController pod
          logs: oc logs -f -n {{ "{{" }} $labels.namespace {{ "}}" }} machine-config-controller-xxxxx
          -c machine-config-controller'
        summary: Triggers when nodes in a pool have overlapping labels such as master,
          worker, and a custom label therefore a choice must be made as to which is
          honored.
      expr: |
        mcc_pool_alert > 0
      labels:
        #namespace: openshift-machine-config-operator
        severity: warning
        customer: "true"
        namespace: {{ .Values.namespace }}
