apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: custom-alerts
  namespace: {{ .Values.namespace }}
  name: olm-alert-rules
spec:
  groups:
  - name: olm.csv_abnormal.rules
    rules:
    - alert: CsvAbnormalFailedOver2Min
      annotations:
        description: Failed to install Operator {{ "{{" }} $labels.name {{ "}}" }} version {{ "{{" }} $labels.version
          {{ "}}" }}. Reason-{{ "{{" }} $labels.reason {{ "}}" }}
        summary: CSV failed for over 2 minutes
      expr: last_over_time(csv_abnormal{phase="Failed"}[5m])
      for: 2m
      labels:
        severity: warning
        customer: "true"
        namespace: {{ .Values.namespace }}
    - alert: CsvAbnormalOver30Min
      annotations:
        description: Failed to install Operator {{ "{{" }} $labels.name {{ "}}" }} version {{ "{{" }} $labels.version
          {{ "}}" }}. Phase-{{ "{{" }} $labels.phase {{ "}}" }} Reason-{{ "{{" }} $labels.reason {{ "}}" }}
        summary: CSV abnormal for over 30 minutes
      expr: last_over_time(csv_abnormal{phase=~"(Replacing|Pending|Deleting|Unknown)"}[5m])
      for: 30m
      labels:
        severity: warning
        customer: "true"
        namespace: {{ .Values.namespace }}
  - name: olm.installplan.rules
    rules:
    - alert: InstallPlanStepAppliedWithWarnings
      annotations:
        description: The API server returned a warning during installation or upgrade
          of an operator. An Event with reason "AppliedWithWarnings" has been created
          with complete details, including a reference to the InstallPlan step that
          generated the warning.
        summary: API returned a warning when modifying an operator
      expr: sum by(namespace) (increase(installplan_warnings_total[5m])) > 0
      labels:
        severity: warning
        customer: "true"
        namespace: {{ .Values.namespace }}
