apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: custom-alerts
  namespace: {{ .Values.namespace }}
  name: podsecurity
spec:
  groups:
  - name: pod-security-violation
    rules:
    - alert: PodSecurityViolation
      annotations:
        description: A workload (pod, deployment, daemonset, ...) was created somewhere
          in the cluster but it did not match the PodSecurity "{{ "{{" }} $labels.policy_level
          {{ "}}" }}" profile defined by its namespace either via the cluster-wide configuration
          (which triggers on a "restricted" profile violations) or by the namespace
          local Pod Security labels. Refer to Kubernetes documentation on Pod Security
          Admission to learn more about these violations.
        summary: One or more workloads users created in the cluster don't match their
          Pod Security profile
      expr: |
        sum(increase(pod_security_evaluations_total{decision="deny",mode="audit",resource="pod",ocp_namespace=""}[1d])) by (policy_level, ocp_namespace) > 0
      labels:
        #namespace: openshift-kube-apiserver
        severity: info
        customer: "true"
        namespace: {{ .Values.namespace }}
    - alert: PodSecurityViolation
      annotations:
        description: A workload (pod, deployment, daemonset, ...) was created in namespace
          "{{ "{{" }} $labels.ocp_namespace {{ "}}" }}" but it did not match the PodSecurity "{{ "{{" }} $labels.policy_level
          {{ "}}" }}" profile defined by its namespace either via the cluster-wide configuration
          (which triggers on a "restricted" profile violations) or by the namespace
          local Pod Security labels. Refer to Kubernetes documentation on Pod Security
          Admission to learn more about these violations.
        summary: One or more workloads in platform namespaces of the cluster don't
          match their Pod Security profile
      expr: |
        sum(increase(pod_security_evaluations_total{decision="deny",mode="audit",resource="pod",ocp_namespace!=""}[1d])) by (policy_level, ocp_namespace) > 0
      labels:
        #namespace: openshift-kube-apiserver
        severity: info
        customer: "true"
        namespace: {{ .Values.namespace }}
