helper-status-checker:
  enabled: true
  approver: true
  checks:
    - operatorName: aap-operator
      subscriptionName: ansible-automation-platform-operator
      namespace:
        name: aap
      serviceAccount:
        name: "status-checker"

csv: ""
roleArn: ""
region: ""
