apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.roleArn }}
  name: {{ .Values.serviceAccount }}
  namespace: openshift-logging
